### ISSUE TITLE
Error in negating vector

### ISSUE THREAD

**Issue by Pessimistress** [stackgl/glsl-transpiler#44]
source: `vec3 x = vec3(1.0); vec3 y = -x;`
transpiled: `var x = [1, 1, 1]; var y = -x;`
output: `y: NaN`

source: `vec3 f() { return vec3(1.0); } vec3 x = -f();`
transpiled: `function f () { return [1, 1, 1]; } var x = -f();`
output: `x: NaN`

**Comment by dy** [comment]
@Pessimistress fixed in @1.8.1. Thanks for the gotcha.
There seems to be other related bugs somewhere around.

**Comment by Pessimistress** [comment]
This is still not working per 1.8.2.

The following code:
```glsl
vec3 f() { return vec3(3.); } vec3 x = -f();
```
is transpiled to
```js
function f () {
  return [3., 3., 3.];
};
var x = f().map(function (_) {return this - _;}, null);
```

Which yields `[NaN, NaN, NaN]`.

It seems that when `thisArg: null` is provided to `Array.prototype.map`, it falls back to the global context. You can test this by running `[1].map(function (_) {return this;}, null)` in either Node or browser.

**Comment by dy** [comment]
Fixed in 1.8.3 as 
```js
var x = f().map(function (_) {return -_;});
```

**Comment by Pessimistress** [comment]
Works perfectly, thank you!
